version: "3.8"

volumes:
  db-store:

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./${PROJECT_DIR:-laravel}:/${PROJECT_DIR:-laravel}
      - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./conf/httpd.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      DOCUMENT_ROOT: /${PROJECT_DIR:-laravel}/public
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME:-laravel_db}
      DB_USERNAME: ${DB_USERNAME:-username}
      DB_PASSWORD: ${DB_PASSWORD:-userpass}
    working_dir: /${PROJECT_DIR:-laravel}
    # restart: always

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE:-Asia/Tokyo}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./conf/mysql.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: ${DB_NAME:-laravel_db}
      MYSQL_USER: ${DB_USERNAME:-username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    # restart: always
