version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ../${PROJECT_DIR:-laravel}:/${PROJECT_DIR:-laravel}
      - ../conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../conf/httpd.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      DOCUMENT_ROOT: /${PROJECT_DIR:-laravel}/public
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME:-laravel_local}
      DB_USERNAME: ${DB_USERNAME:-username}
      DB_PASSWORD: ${DB_PASSWORD:-userpass}
    working_dir: /${PROJECT_DIR:-laravel}
    # restart: always
